app01/urls.py
from django.conf.urls import url
from app01 import views

urlpatterns = [
    url(r'^addbook/$', views.addbook, name='addbook'),
    url('delete/(\d+)', views.delbook, name="delbook"),
    url('edit/(\d+)', views.editbook, name="editbook"),
    url(r'^$', views.books,name="index"),

]

mysite/urls.py
from django.contrib import admin

from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path('book/', include(('app01.urls', 'book'), namespace='book')),
]

app01/models.py
from django.db import models


# Create your models here.

class Book(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)
    price = models.DecimalField(max_digits=8, decimal_places=2)  # 999999.99
    pub_date = models.DateTimeField()  # "2012-12-12"
    publish = models.CharField(max_length=32)

    def __str__(self):
        return self.title

app02/models.py
from django.db import models

# Create your models here.


class Food(models.Model):
    title=models.CharField(max_length=32)
    price=models.DecimalField(max_digits=8,decimal_places=2,default=100)

app01/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from app01.models import Book
# Create your views here.

import datetime

from app01.models import Book


def addbook(request):
    # book=Book(title="python1",price=123,pub_date="2015-09-12",publish="pcec01")
    # book.save()
    if request.method == 'GET':
        return render(request, "addbook.html")
    if request.method == 'POST':
        title = request.POST.get("title")
        price = request.POST.get("price")
        pub_date = request.POST.get("pub_date")
        publish = request.POST.get("publish")

        book = Book.objects.create(title=title, price=price, pub_date=pub_date, publish=publish)

        return redirect(reverse('book:index'))


def books(request):
    book_list = Book.objects.filter()
    context = {
        'bookList': book_list,
    }
    return render(request, "books.html", context)


def delbook(request, delete_book_id):
    Book.objects.filter(nid=delete_book_id).delete()
    return redirect(reverse('book:index'))


def editbook(request,edit_book_id):
    """
    编辑功能：
       #Book.objects.filter(nid=edit_book_id).update(price=111)
       #Book.objects.filter(price=111).update(publish="南京出版社")

    :param request:
    :param edit_book_id:
    :return:
    """
    if request.method=="GET":
        edit_book = Book.objects.filter(nid=edit_book_id)[0]
        return render(request, "editbook.html", {"edit_book": edit_book})

    else:
        title = request.POST.get("title")
        price = request.POST.get("price")
        pub_date = request.POST.get("pub_date")
        publish = request.POST.get("publish")
        Book.objects.filter(nid=edit_book_id).update(title=title,
                                                     price=price,
                                                     pub_date=pub_date,
                                                     publish=publish)



        return redirect(reverse("book:index"))

app02/views.py
from django.shortcuts import render

# Create your views here.

templates/addbook.html
{% extends "base.html" %}
{% block header_con %}
    <h1>add book page</h1>
{% endblock header_con %}
{% block contain %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <table class="table table-striped table-hover">
                <form action="" method="post" class="form-inline" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label  for="title">title</label>
                        <input type="text" class="form-control" name="title" id="" placeholder="title">
                    </div>
                    <div class="form-group">
                        <label  for="price">price</label>
                        <input type="text" class="form-control" name="price" id="" placeholder="price">
                    </div>
                     <div class="form-group">
                        <label  for="pub_date">pub_date</label>
                        <input type="date" class="form-control" name="pub_date" id="" placeholder="pub_date">
                    </div>
                     <div class="form-group">
                        <label  for="publish">publish</label>
                        <input type="text" class="form-control" name="publish" id="" placeholder="publish">
                    </div>



                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </table>
        </div>
    </div>
</div>



{% endblock contain%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script href="{% static 'js/bootstrap.min.js' %}"></script>
    <title>{% block title %}{% endblock title %}</title>
    <style>
        .header {
            height: 50px;
            width:100%;
            background:red;
        }
        .contain {
            height: 500px;
            width:100%;
            background:green;
        }
        .footer {
            height: 50px;
            width:100%;
            background:gray;
        }
    </style>
</head>
<body>
<div class="header">
    {% block header_con %}
        <h1>This is header Page</h1>
    {% endblock header_con %}


</div>
{% block contain %}
<div class="contain">

    <h1>This is contain</h1>
</div>
{% endblock contain %}
<div class="footer">

    <h1>This is footer</h1>
</div>
</body>
</html>

templates/books.html
{% extends "base.html" %}
{% block title %}book page{% endblock title %}

{% block header_con %}
    <h1>bookList page</h1>
{% endblock header_con %}
{% block contain %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="/book/addbook/" class="btn btn-primary">add book</a>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>nid</th>
                    <th>title</th>
                    <th>price</th>
                    <th>date</th>
                    <th>press</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for book in bookList %}
                <tr>
                    <td>{{ book.nid }}</td>
                    <td>{{ book.title }}</td>
                    <td>{{ book.price }}</td>
                    <td>{{ book.pub_date }}</td>
                    <td>{{ book.publish }}</td>
                    <td>
                        <a href="{% url 'book:editbook' book.nid %}" class="btn btn-warning btn-sm">编辑</a>
                        <a href="/book/delete/{{ book.nid }}" class="btn btn-danger btn-sm">删除</a>
                    </td>

                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>



{% endblock contain%}

templates/editbook.html
{% extends "base.html" %}
{% block header_con %}
    <h1>edit book page</h1>
{% endblock header_con %}
{% block contain %}
<div class="container">
    <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">书籍名称</label>
                    <input type="text" value="{{ edit_book.title }}" class="form-control" id="title" placeholder="Title" name="title">
                </div>
                <div class="form-group">
                    <label for="price">价格</label>
                    <input type="text" value="{{ edit_book.price }}" class="form-control" id="price" placeholder="Price" name="price">
                </div>
                <div class="form-group">
                    <label for="pub_date">出版日期</label>
                    <input type="date" value="{{ edit_book.pub_date|date:'Y-m-d' }}" class="form-control" id="pub_date" placeholder="pub_date" name="pub_date">
                </div>

                <div class="form-group">
                    <label for="publish">出版社</label>
                    <input type="text" value="{{ edit_book.publish }}" class="form-control" id="publish" placeholder="publish" name="publish">
                </div>


                <button type="submit" class="btn btn-success pull-right">Submit</button>
            </form>
        </div>
    </div>
</div>
</div>



{% endblock contain%}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index _test</title>
    <style>
        .header {
            height: 50px;
            width:100%;
            background:red;
        }
        .contain {
            height: 500px;
            width:100%;
            background:green;
        }
        .footer {
            height: 50px;
            width:100%;
            background:gray;
        }
    </style>
</head>
<body>
<div class="header">

    <h1>This is index Page</h1>
</div>
<div class="contain">

    <h1>This is contain</h1>
</div>
<div class="footer">

    <h1>This is footer</h1>
</div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'login' %}" method="post" class="form-horizontal" role="form">
    {% csrf_token %}
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">用户名</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="user" placeholder="">
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">密码</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="pwd" placeholder="">
        </div>
    </div>







    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button type="submit" class="btn btn-primary">提交</button>
        </div>
    </div>
</form>

<ul>
   {% for foo in content %}
       <li>{{ foo }}</li>
   {% endfor %}
</ul>
</body>
</html>